import { NextResponse } from 'next/server';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

export async function POST(req: Request) {
    try {
        const data = await req.json();
        const { financialData, riskScore, loanDecision, fraudAlerts, riskInsights } = data;

        const pdfDoc = await PDFDocument.create();
        const timesRomanFont = await pdfDoc.embedFont(StandardFonts.TimesRoman);
        const timesBoldFont = await pdfDoc.embedFont(StandardFonts.TimesRomanBold);

        const page = pdfDoc.addPage([595.28, 841.89]); // A4
        const { width, height } = page.getSize();
        let y = height - 50;

        const drawText = (text: string, size: number, font = timesRomanFont, color = rgb(0, 0, 0)) => {
            const maxChars = Math.floor((width - 100) / (size * 0.5));
            const words = text.split(' ');
            let line = '';
            for (const word of words) {
                if ((line + word).length > maxChars) {
                    if (y < 60) return;
                    page.drawText(line.trim(), { x: 50, y, size, font, color });
                    y -= size + 6;
                    line = word + ' ';
                } else {
                    line += word + ' ';
                }
            }
            if (line.trim() && y >= 60) {
                page.drawText(line.trim(), { x: 50, y, size, font, color });
                y -= size + 10;
            }
        };

        const drawSectionHeader = (text: string) => {
            y -= 10;
            if (y < 80) return;
            drawText(text, 14, timesBoldFont, rgb(0, 0.2, 0.6));
            page.drawLine({
                start: { x: 50, y: y + 8 },
                end: { x: width - 50, y: y + 8 },
                thickness: 1,
                color: rgb(0.8, 0.8, 0.8),
            });
            y -= 5;
        };

        // ── Header ─────────────────────────────────────────────────────────────
        drawText('CREDIT APPRAISAL MEMO (CAM)', 20, timesBoldFont, rgb(0, 0.2, 0.5));
        drawText('AI-Generated by IntelliCredit — Powered by OpenAI', 10, timesRomanFont, rgb(0.4, 0.4, 0.4));
        y -= 10;
        drawText(`Date: ${new Date().toLocaleDateString()}`, 12);

        // ── 1. Company Overview ─────────────────────────────────────────────────
        drawSectionHeader('1. Company Overview');
        drawText(`Company Name: ${financialData?.companyName || 'N/A'}`, 12);
        drawText(`Sector: Manufacturing / Trading (Inferred)`, 12);

        // ── 2. Financial Analysis ───────────────────────────────────────────────
        drawSectionHeader('2. Financial Analysis (AI-Extracted)');
        const fmt = (val: number) => `INR ${(val || 0).toLocaleString('en-IN')}`;
        drawText(`Total Revenue: ${fmt(financialData?.revenue)}`, 12);
        drawText(`Net Profit: ${fmt(financialData?.netProfit)}`, 12);
        drawText(`Total Debt: ${fmt(financialData?.totalDebt)}`, 12);
        drawText(`Total Assets: ${fmt(financialData?.totalAssets)}`, 12);
        drawText(`Net Worth: ${fmt(financialData?.netWorth)}`, 12);
        drawText(`Cash Flow: ${fmt(financialData?.cashFlow)}`, 12);
        drawText(`GST Turnover: ${fmt(financialData?.gstTurnover)}`, 12);
        drawText(`Bank Deposits: ${fmt(financialData?.bankDeposits)}`, 12);

        // ── 3. AI Risk Insights ─────────────────────────────────────────────────
        if (riskInsights && riskInsights.length > 0) {
            drawSectionHeader('3. AI Risk Insights');
            for (const insight of riskInsights) {
                drawText(`• ${insight}`, 11);
            }
        }

        // ── 4. Fraud Indicators ─────────────────────────────────────────────────
        drawSectionHeader('4. Risk & Fraud Indicators');
        if (fraudAlerts && fraudAlerts.length > 0) {
            fraudAlerts.forEach((alert: any) => {
                drawText(
                    `• [${alert.type.toUpperCase()}] ${alert.title}: ${alert.description}`,
                    11, timesRomanFont, rgb(0.8, 0.1, 0.1)
                );
            });
        } else {
            drawText('• No major fraud indicators detected by AI.', 12, timesRomanFont, rgb(0.1, 0.6, 0.1));
        }

        // ── 5. Five Cs Evaluation ───────────────────────────────────────────────
        drawSectionHeader('5. Five Cs of Credit Evaluation');
        drawText(`Character Score: ${riskScore?.character}/100`, 12);
        drawText(`Capacity Score: ${riskScore?.capacity}/100`, 12);
        drawText(`Capital Score: ${riskScore?.capital}/100`, 12);
        drawText(`Collateral Score: ${riskScore?.collateral}/100`, 12);
        drawText(`Conditions Score: ${riskScore?.conditions}/100`, 12);
        drawText(`FINAL RISK SCORE: ${riskScore?.overall}/100 (${loanDecision?.riskLevel})`, 14, timesBoldFont);

        // ── 6. Loan Recommendation ──────────────────────────────────────────────
        drawSectionHeader('6. Final Loan Recommendation');
        drawText(
            `Decision Status: ${loanDecision?.status}`, 14, timesBoldFont,
            loanDecision?.status === 'REJECTED' ? rgb(0.8, 0, 0) : rgb(0, 0.6, 0)
        );
        drawText(`Recommended Amount: ${fmt(loanDecision?.amount)}`, 12, timesBoldFont);
        drawText(`Suggested Interest Rate: ${loanDecision?.interestRate}% p.a.`, 12);
        if (loanDecision?.reasoning) {
            drawText(`Reasoning: ${loanDecision.reasoning}`, 11, timesRomanFont, rgb(0.3, 0.3, 0.3));
        }

        page.drawText('AI-Generated Report — IntelliCredit AI | Powered by OpenAI GPT-4o-mini', {
            x: 50, y: 30, size: 9, font: timesRomanFont, color: rgb(0.5, 0.5, 0.5),
        });

        const pdfBytes = await pdfDoc.save();

        return new NextResponse(Buffer.from(pdfBytes), {
            status: 200,
            headers: {
                'Content-Type': 'application/pdf',
                'Content-Disposition': `attachment; filename="CAM_${financialData?.companyName?.replace(/\s+/g, '_') || 'Report'}.pdf"`,
            },
        });

    } catch (error) {
        console.error('Failed to generate CAM report:', error);
        return NextResponse.json({ success: false, error: 'Failed to generate PDF' }, { status: 500 });
    }
}
